---
- name: "Processing vpc {{ item_vpcsubnet.name }} on cloud {{ item_cloud.name }}"
  debug:
    msg: "{{ item_vpcsubnet.name }} , {{ item_vpcsubnet.cidr }}, {{ item_vpcsubnet.gateway }}, {{ item_vpcsubnet.dhcp_enable }}, {{ item_vpcsubnet.primary_dns }}, {{ item_vpcsubnet.secondary_dns }}, {{ item_vpcsubnet.availability_zone }}, {{ item_vpcsubnet.net }}"
    verbosity: 3

- name: "Request token from AUTH API to create vpc {{ item_vpc.name }} on cloud {{ item_cloud.name }}"
  uri:
    url: "{{ auth_url }}/auth/tokens"
    method: POST
    body_format: raw
    follow_redirects: all
    status_code: 201
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('template', '../templates/fe-token.json.j2',convert_data=True)|to_json }}"
  register: token

- name: "Request vpc list from AUTH API to  create vpcsubnet {{ item_vpcsubnet.name }} on cloud {{ item_cloud.name }}"
  uri:
    url: "{{ auth_url_vpc }}/{{ project_id }}/vpcs"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: vpclist

- name: "print vpclist"
  debug:
    var: vpclist.json
    verbosity: 3

- name: "Send request to API to  create vpcsubnet {{ item_vpcsubnet.name }} on cloud {{ item_cloud.name }}"
  uri:
    url: "{{ auth_url_vpc }}/{{ project_id }}/subnets"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', '../templates/fe-vpcsubnet.json.j2')|to_json }}"
  register: subnet

- debug:
    msg: "{{ subnet }}"
    verbosity: 3
