---
- name: "Processing vpc {{ item_vpc.name }} on cloud {{ item_cloud.name }}"
  debug:
    msg: "{{ item_vpc.name }} , {{ item_vpc.cidr }}"
    verbosity: 3

- name: "Request token from AUTH API to create vpc {{ item_vpc.name }} on cloud {{ item_cloud.name }}"
  uri:
    url: "{{ auth_url }}/auth/tokens"
    method: POST
    body_format: raw
    follow_redirects: all
    status_code: 201
    timeout: 180
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('template', '../templates/fe-token.json.j2',convert_data=True)|to_json }}"
  register: token

- name: "Send request to API to create vpc {{ item_vpc.name }} on cloud {{ item_cloud.name }}"
  uri:
    url: "{{ auth_url_vpc }}/{{ project_id }}/vpcs"
    method: POST
    body_format: raw
    follow_redirects: all
    timeout: 180
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', '../templates/fe-vpc.json.j2')|to_json }}"
  register: vpc

- name: "vpc created"
  debug:
    msg: "{{ vpc }}"
    verbosity: 3
