---
- name: "Processing per cloud domains for cloud {{ item_cloud.name }}"
  include: create_domain.yml
  with_items: "{{ item_cloud.domains|default([]) }}"
  loop_control:
    loop_var: item_domain
  tags:
    - domains

- name: "Processing per cloud projects for cloud {{ item_cloud.name }}"
  include: create_project.yml
  with_items: "{{ item_cloud.projects|default([]) }}"
  loop_control:
    loop_var: item_project
  tags:
    - projects

- name: "Processing per cloud users for cloud {{ item_cloud.name }}"
  include: create_user.yml
  with_items: "{{ item_cloud.users|default([]) }}"
  loop_control:
    loop_var: item_user
  tags:
    - users

- name: "Processing per cloud roles for cloud {{ item_cloud.name }}"
  include: create_role.yml
  with_items: "{{ item_cloud.roles|default([]) }}"
  loop_control:
    loop_var: item_role
  tags:
    - roles

- name: "Processing per cloud user roles for cloud {{ item_cloud.name }}"
  include: create_user_role.yml
  with_items: "{{ item_cloud.user_roles|default([]) }}"
  loop_control:
    loop_var: item_user_role
  tags:
    - user_roles

- name: "Processing per cloud quotas for cloud {{ item_cloud.name }}"
  include: create_quota.yml
  with_items: "{{ item_cloud.quotas|default([]) }}"
  loop_control:
    loop_var: item_quota
  tags:
    - quotas

- name: "Processing per cloud networks for cloud {{ item_cloud.name }}"
  include: create_network.yml
  with_items: "{{ item_cloud.networks|default([]) }}"
  loop_control:
    loop_var: item_network
  tags:
    - networks

- name: "Processing per cloud subnets for cloud {{ item_cloud.name }}"
  include: create_subnet.yml
  with_items: "{{ item_cloud.subnets|default([]) }}"
  loop_control:
    loop_var: item_subnet
  tags:
    - subnets

- name: "Processing per cloud routers for cloud {{ item_cloud.name }}"
  include: create_router.yml
  with_items: "{{ item_cloud.routers|default([]) }}"
  loop_control:
    loop_var: item_router
  tags:
    - routers

- name: "Processing per cloud flavors for cloud {{ item_cloud.name }}"
  include: create_flavor.yml
  with_items: "{{ item_cloud.flavors|default([]) }}"
  loop_control:
    loop_var: item_flavor
  tags:
    - flavors

- name: "Processing per cloud images for cloud {{ item_cloud.name }}"
  include: create_image.yml
  with_items: "{{ item_cloud.images|default([]) }}"
  loop_control:
    loop_var: item_image
  tags:
    - images

- name: "Processing per cloud security_groups for cloud {{ item_cloud.name }}"
  include: create_security_group.yml
  with_items: "{{ item_cloud.security_groups|default([]) }}"
  loop_control:
    loop_var: item_security_group
  tags:
    - security_groups

- name: "Processing per cloud security_group_rules for cloud {{ item_cloud.name }}"
  include: create_security_group_rule.yml
  with_items: "{{ item_cloud.security_groups_rules|default([]) }}"
  loop_control:
    loop_var: item_security_group_rule
  tags:
    - security_groups_rules

- name: "Processing ports resources for cloud {{ item_cloud.name }}"
  include: create_port.yml
  with_items: "{{ clouds|selectattr('name', 'equalto', item_cloud)|map(attribute='ports')|list }}"
  loop_control:
    loop_var: item_port
  when: "{{ 'ports' in clouds|selectattr('name', 'equalto', item_cloud)|list|first }}"
  tags:
    - ports

- name: "Processing per cloud keypairs for cloud {{ item_cloud.name }}"
  include: create_keypair.yml
  with_items: "{{ item_cloud.keypairs|default([]) }}"
  loop_control:
    loop_var: item_keypair
  tags:
    - keypairs

- name: "Processing per cloud volumes for cloud {{ item_cloud.name }}"
  include: create_volume.yml
  with_items: "{{ item_cloud.volumes|default([]) }}"
  loop_control:
    loop_var: item_volume
  tags:
    - volumes

- name: "Processing per cloud server_groups for cloud {{ item_cloud.name }}"
  include: create_server_group.yml
  with_items: "{{ item_cloud.server_groups|default([]) }}"
  loop_control:
    loop_var: item_server_group
  tags:
    - server_groups

- name: "Processing per cloud servers for cloud {{ item_cloud.name }}"
  include: create_server.yml
  with_items: "{{ item_cloud.servers|default([]) }}"
  loop_control:
    loop_var: item_server
  tags:
    - servers

- name: "Processing per cloud floating_ips for cloud {{ item_cloud.name }}"
  include: create_floating_ip.yml
  with_items: "{{ item_cloud.floating_ips|default([]) }}"
  loop_control:
    loop_var: item_floating_ip
  tags:
    - floating_ips
