---
- include: generate_keypair.yml
  when: generate_keypair|bool

- name: "Processing server_group for {{ item_server.name }} on cloud {{ item_cloud.name }}"
  set_fact:
    sc_hint: 'group={{ hostvars["oarcb-"+item_server.server_group].group_id }}'
  when: "( item_server.server_group is defined )"

- name: "Processing server {{ item_server.name }} with nics defined on cloud {{ item_cloud.name }}"
  os_server:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_server.state|default(omit) }}"
    name: "{{ item_server.name.partition('.')[0] }}{{ '' if item_server.node_count is not defined else item }}{{ item_server.name.partition('.')[1] + item_server.name.partition('.')[2] }}"
    image: "{{ item_server.image }}"
    auto_ip: "{{ item_server.auto_ip|default(omit) }}"
    boot_from_volume: "{{ item_server.boot_from_volume|default(omit) }}"
    boot_volume: "{{ item_server.boot_volume|default(omit) }}"
    config_drive: "{{ item_server.config_drive|default(omit) }}"
    flavor: "{{ item_server.flavor|default(omit) }}"
    flavor_include: "{{ item_server.flavor_include|default(omit) }}"
    flavor_ram: "{{ item_server.flavor_ram|default(omit) }}"
    floating_ip_pools: "{{ item_server.floating_ip_pools|default(omit) }}"
    floating_ips: "{{ item_server.floating_ips|default(omit) }}"
    image_exclude: "{{ item_server.image_exclude|default(omit) }}"
    key: "{{ item_server.key|default(omit) }}"
    key_name: "{{ cl_generated_keypair_name|default(item_server.key_name)|default(omit) }}"
    meta: "{{ item_server.meta|default(omit) }}"
    network: "{{ item_server.network|default(omit) }}"
    #nics: "{{ item_server.nics|default(omit) }}"
    nics: "port-name={{ item_server.nics|join(',port-name=') }}"
    #scheduler_hints: "{{ item_server.scheduler_hints|default(omit) }}"
    scheduler_hints: "{{ sc_hint|default(omit) }}"
    security_groups: "{{ item_server.security_groups|default(omit) }}"
    terminate_volume: "{{ item_server.terminate_volume|default(omit) }}"
    userdata: "{{ item_server.userdata|default(omit) }}"
    volume_size: "{{ item_server.volume_size|default(omit) }}"
    volumes: "{{ item_server.volumes|default(omit) }}"
    availability_zone: "{{ item_server.availability_zone|default(omit) }}"
    region_name: "{{ item_cloud.region_name|default(omit) }}"
    validate_certs: "{{ os_validate_certs }}"
    wait: yes
  with_sequence: start=1 end={{ item_server.node_count|default(1) }} format=%02x
  register: os_server_result
  when: "( item_server.nics is defined )"

- add_host: name={{ item.server.name }} groups=cl_servers_just_created ansible_ssh_host={{ item.server.public_v4 }}
  with_items: "{{ os_server_result.results|default([]) }}"
  when: "( item_server.nics is defined )"

- name: "Processing server {{ item_server.name }} with nics not defined on cloud {{ item_cloud.name }}"
  os_server:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_server.state|default(omit) }}"
    name: "{{ item_server.name.partition('.')[0] }}{{ '' if item_server.node_count is not defined else item }}{{ item_server.name.partition('.')[1] + item_server.name.partition('.')[2] }}"
    image: "{{ item_server.image }}"
    auto_ip: "{{ item_server.auto_ip|default(omit) }}"
    boot_from_volume: "{{ item_server.boot_from_volume|default(omit) }}"
    boot_volume: "{{ item_server.boot_volume|default(omit) }}"
    config_drive: "{{ item_server.config_drive|default(omit) }}"
    flavor: "{{ item_server.flavor|default(omit) }}"
    flavor_include: "{{ item_server.flavor_include|default(omit) }}"
    flavor_ram: "{{ item_server.flavor_ram|default(omit) }}"
    floating_ip_pools: "{{ item_server.floating_ip_pools|default(omit) }}"
    floating_ips: "{{ item_server.floating_ips|default(omit) }}"
    image_exclude: "{{ item_server.image_exclude|default(omit) }}"
    key: "{{ item_server.key|default(omit) }}"
    key_name: "{{ cl_generated_keypair_name|default(item_server.key_name)|default(omit) }}"
    meta: "{{ item_server.meta|default(omit) }}"
    network: "{{ item_server.network|default(omit) }}"
    nics: "{{ item_server.nics|default(omit) }}"
    #scheduler_hints: "{{ item_server.scheduler_hints|default(omit) }}"
    scheduler_hints: "{{ sc_hint|default(omit) }}"
    security_groups: "{{ item_server.security_groups|default(omit) }}"
    terminate_volume: "{{ item_server.terminate_volume|default(omit) }}"
    userdata: "{{ item_server.userdata|default(omit) }}"
    volume_size: "{{ item_server.volume_size|default(omit) }}"
    volumes: "{{ item_server.volumes|default(omit) }}"
    availability_zone: "{{ item_server.availability_zone|default(omit) }}"
    region_name: "{{ item_cloud.region_name|default(omit) }}"
    validate_certs: "{{ os_validate_certs }}"
    wait: yes
  with_sequence: start=1 end={{ item_server.node_count|default(1) }} format=%02x
  register: os_server_result2
  when: "( item_server.nics is not defined )"

- add_host: name={{ item.server.name }} groups=cl_servers_just_created ansible_ssh_host={{ item.server.public_v4 }}
  with_items: "{{ os_server_result2.results|default([]) }}"
  when: "( item_server.nics is not defined )"
